### ISSUE TITLE
eval_tidy doesn't evaluate formulas

### ISSUE THREAD

**Issue by alistaire47** [hadley/rlang#103]
When passed a formula, `eval_tidy` just returns the formula and environment instead of actually evaluating:

``` r
library(rlang)

str(eval_tidy(~ mean(mpg), mtcars))
#> Class 'formula'  language ~mean(mpg)
#>   ..- attr(*, ".Environment")=<environment: 0x7fd501bd2630>

str(eval_tidy(quo( mean(mpg) ), mtcars))
#>  num 20.1
```

(When run manually, the environment is `R_GlobalEnv`; the pointer is a result of `reprex::reprex`/knitr evaluation.) 

This is currently breaking the purrr devel version's `list_update` and `update_list`. On the CRAN version, formulas in `update_list` evaluate:

``` r
# example from devel ?purrr::list_update
library(purrr)

x <- list(x = 1:10, y = 4, z = list(a = 1, b = 2))

update_list(x, z = ~ x + y) %>% str()
#> List of 3
#>  $ x: int [1:10] 1 2 3 4 5 6 7 8 9 10
#>  $ y: num 4
#>  $ z: num [1:10] 5 6 7 8 9 10 11 12 13 14
```

but on the rlang-powered devel version,

``` r
list_update(x, z = ~ x + y) %>% str()
#> List of 3
#>  $ x: int [1:10] 1 2 3 4 5 6 7 8 9 10
#>  $ y: num 4
#>  $ z:Class 'formula'  language ~x + y
#>   .. ..- attr(*, ".Environment")=<environment: 0x7fd390d0a030>

update_list(x, z = ~ x + y) %>% str()
#> List of 3
#>  $ x: int [1:10] 1 2 3 4 5 6 7 8 9 10
#>  $ y: num 4
#>  $ z:Class 'formula'  language ~x + y
#>   .. ..- attr(*, ".Environment")=<environment: 0x7fd390d0a030>

list_update(x, z = rlang::quo(x + y)) %>% str()
#> List of 3
#>  $ x: int [1:10] 1 2 3 4 5 6 7 8 9 10
#>  $ y: num 4
#>  $ z: num [1:10] 5 6 7 8 9 10 11 12 13 14
```

I can file the issue there if you like, but `eval_tidy` is clearly the underlying culprit.

**Comment by lionel-** [comment]
That's by design, bare formulas are not treated as quosures anymore. I'll look into updating purrr.

**Comment by alistaire47** [comment]
Ok, then the docs for `?eval_tidy` are misleading, as they're shot-through with the word "formula". They also claim 

> `eval_tidy_rhs` evaluates the RHS of a formula and `eval_tidy_lhs()` evaluates the LHS. `eval_tidy()` is a shortcut for `eval_tidy_rhs()` since that is what you most commonly need.

which is not true, as the `eval_tidy_*` forms turn the respective half into a quosure, which `eval_tidy` doesn't:

``` r
rlang::eval_tidy_lhs(1 + 2 ~ 3 + 4)
#> 3 ~ 3 + 4
#> <environment: 0x7f8a034fb630>

rlang::eval_tidy_rhs(1 + 2 ~ 3 + 4)
#> 1 + 2 ~ 7
#> <environment: 0x7f8a034fb630>

rlang::eval_tidy(1 + 2 ~ 3 + 4)
#> 1 + 2 ~ 3 + 4
#> <environment: 0x7f8a034fb630>
```

Really, I'm not sure what the purpose of the `eval_tidy_*` versions is unless they're supposed to evaluate functions. Or maybe I'm just massively confused.

**Comment by lionel-** [comment]
they will be removed and the tidyeval docs will be rewritten.
