### ISSUE TITLE
as_list() for factors

### ISSUE THREAD

**Issue by krlmlr** [hadley/rlang#118]
Is this intended?

``` r
rlang::as_list(factor(c(a = "a", b = "b")))
#> $a
#> [1] 1
#> 
#> $b
#> [1] 2
```

I was looking for a base substitute which behaves interestingly, too.

``` r
as.list(factor(c(a = 1, b = 2)))
#> [[1]]
#> a 
#> 1 
#> Levels: 1 2
#> 
#> [[2]]
#> b 
#> 2 
#> Levels: 1 2
```

**Comment by hadley** [comment]
I think anything related to S3 is currently out of scope for rlang.

**Comment by krlmlr** [comment]
Thanks, I should have looked into the docs before posting.
