### ISSUE TITLE
eval_tidy no longer eval-ing

### ISSUE THREAD

**Issue by jaminday** [hadley/rlang#119]
`eval_tidy()` doesn't seem to be working in the current version. Using rlang v0.0.0.9019 I get the following:
```
> eval_tidy(~ 1 + 2 + 3)
~ 1 + 2 + 3

> eval_tidy(~ cyl, mtcars)
~cyl
```

**Comment by lionel-** [comment]
it's been that way for a while. See updated documentation in https://github.com/hadley/rlang/pull/117

**Comment by lionel-** [comment]
(only quosures self-evaluate: `eval_tidy(quo(1 + 2 + 3))`)

**Comment by jaminday** [comment]
My mistake - was looking at older documentation.
Thanks for clarifying.
