### ISSUE TITLE
Provide way to terminate current execution

### ISSUE THREAD

**Issue by hadley** [hadley/rlang#35]
I don't know if this is possible, but it would be really useful to have something like `return()` that could be called from top-level code being executed by `source()`

i.e. in examples instead of 

```R
if (requireNamespace("RSQLite", quietly = TRUE)) {
   ...
}
```

I'd like to be able to do

```R
if (!requireNamespace("RSQLite", quietly = TRUE)) 
  end()

...
```

**Comment by lionel-** [comment]
maybe `return_to(topenv())` would work?

**Comment by lionel-** [comment]
oops no, `topenv()` is about lexical scope.

**Comment by lionel-** [comment]
`rst_jump("abort")` should work.
