### ISSUE TITLE
Packed assertions

### ISSUE THREAD

**Issue by lionel-** [hadley/rlang#37]
would this lead to clearer code than a series of `if ()` and `abort()`?

```r
abort_if(
  !is_scalar_list(x) := "must be a scalar list",
  !inherits(x, "foo") := "'x' must be a 'foo'",
  !inherits(y, "bar") := "`y` must be a `bar`"
)
```

with `warn_if()` and `inform_if()` variants. The error message would be passed directly to `cnd_abort()` so could be typed conditions as well.

**Comment by hadley** [comment]
This feels like a separate package to me (and IMO `~` would feel nicer here)

**Comment by krlmlr** [comment]
Should we reconsider, given that assertthat is too large? Perhaps as a lighter-weight alternative to `stopifnot()` that

- is faster
- gives an error of class `"<pkg-name>_error"`

```r
abort_if_not(
  is_scalar_list(x),
  inherits(x, "foo"),
  inherits(y, "bar")
)
```
