### ISSUE TITLE
paste0() replacement?

### ISSUE THREAD

**Issue by krlmlr** [hadley/rlang#44]
- Should accept only vectors of length 1 or n
- If n == 0, returns `character()`
- Should warn/fail on named arguments other than `sep` or `collapse`
- Should always return UTF-8

Naming suggestion: `glue()`

**Comment by lionel-** [comment]
Please see the glue package.

**Comment by krlmlr** [comment]
Do you have a link?

**Comment by krlmlr** [comment]
Oh, got it.
