### ISSUE TITLE
Self-evaluation of explicit quosures

### ISSUE THREAD

**Issue by jennybc** [hadley/rlang#60]
Apologies for the terrible subject. I have almost no internet, so can't do further research. This is a dplyr error but I suspect the problem is rlang (?).

I noticed this while trying to write an example for someone trying to do `map_*()` inside `filter()`. I'm not exactly sure what the problem is but with dev (purrr + dplyr), no go. With CRAN (purrr + dplyr), all is well. It seems like something that *should* work, so I'm assuming this is a bug not a feature.

CRAN purrr and dplyr

``` r
library(tidyverse)
iris_tibble <- as_tibble(iris)

map_lgl(iris_tibble$Species, ~ grepl("^v", .x))
#>   [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [12] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [23] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [34] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [45] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [56]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [67]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [78]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [89]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [100]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [111]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [122]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [133]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [144]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

iris_tibble %>% 
  filter(map_lgl(Species, ~ grepl("^v", .x)))
#> # A tibble: 100 × 5
#>    Sepal.Length Sepal.Width Petal.Length Petal.Width    Species
#>           <dbl>       <dbl>        <dbl>       <dbl>     <fctr>
#> 1           7.0         3.2          4.7         1.4 versicolor
#> 2           6.4         3.2          4.5         1.5 versicolor
#> 3           6.9         3.1          4.9         1.5 versicolor
#> 4           5.5         2.3          4.0         1.3 versicolor
#> 5           6.5         2.8          4.6         1.5 versicolor
#> 6           5.7         2.8          4.5         1.3 versicolor
#> 7           6.3         3.3          4.7         1.6 versicolor
#> 8           4.9         2.4          3.3         1.0 versicolor
#> 9           6.6         2.9          4.6         1.3 versicolor
#> 10          5.2         2.7          3.9         1.4 versicolor
#> # ... with 90 more rows
```

Dev purrr and dplyr

``` r
library(tidyverse)
iris_tibble <- as_tibble(iris)

map_lgl(iris_tibble$Species, ~ grepl("^v", .x))
#>   [1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [12] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [23] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [34] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
#>  [45] FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [56]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [67]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [78]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#>  [89]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [100]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [111]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [122]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [133]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
#> [144]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE

iris_tibble %>% 
  filter(map_lgl(Species, ~ grepl("^v", .x)))
#> Error in filter_impl(.data, dots): object '.x' not found
```

**Comment by lionel-** [comment]
Hi Jenny,

Formulas will only have one meaning in the tidyeval framework: reified promises. They bundle a quote and an enclosure, you can pass them around, but as soon as they are evaluated in a tidyeval function they self-evaluate their RHS. Because of this, we have kind of the same situation as `.`, whose meaning is overloaded in various places (magrittr, dplyr, purrr), which can cause issues. I think the benefits of full programmability will outweight this inconvenience.

So you will need to "guard" the quosure whenever you use `map()` in a tidyeval function:

```r
as_tibble(iris) %>% filter(purrr::map_lgl(Species, UQF(~ grepl("^v", .x))))
```

Or use an explicit lambda function.

You can see the effects of unquote-guarding with `quosure()` (the most basic NSE function in the tidyeval framework, it just quotes and interpolates the unquote operators):

```r
quosure(map(x, UQF(~ grepl("^v", .x))))
#> ~map(x, `_F`(grepl("^v", .x)))
```

**Comment by lionel-** [comment]
though I agree this has been bothering me as well and I just thought of a possible solution: maybe we could treat `~` as self-guarding during interpolation? 

* `quosure(!! ~foobar)` would return `~~foobar`
* `quosure(~foobar)` would return `` ~`_F`(foobar) ``

I think that should work. If a user write `~foobar` as argument, chances are he means the real thing. And if not unquoting the quosure with `!!` will circumvent unguarding.

I'm not sure yet this will work but worth a try.

**Comment by jennybc** [comment]
The concise formula syntax of CRAN purrr is, I feel, a real advantage. I think it would be worth exploring a way to retain that and not require explicit guarding. To be very selfish, I will have a lot of code that needs to be modified if I have to go back and insert `UQF()` everywhere 😔.

**Comment by hadley** [comment]
Yes, we absolutely need to make sure that existing formulas aren't unquoted.

**Comment by michaelbarton** [comment]
Not sure if this is related but this is the top google hit for the error:

    Evaluation error: could not find function "map".
    Calls: test_check ... as.data.frame -> filter -> filter.tbl_df -> filter_impl -> .Call

I get this from:

    .which     = if(greater_is_better) quo(conf.low) else quo(conf.high)
    .transform = if(greater_is_better) min else max
    .sort      = if(greater_is_better) desc else identity

    coeffs <- model_coefficients %>%
      dplyr::group_by(term) %>%
      dplyr::filter((!!.which) == .transform((!!.which))) %>%
      dplyr::arrange(.sort(!!.which)) %>%
      dplyr::rowwise()
