### ISSUE TITLE
quosures should add class to output

### ISSUE THREAD

**Issue by hadley** [hadley/rlang#68]
And provide `[.quosures` and `is_quosures`.  This will be useful for providing error messages (particularly in the scenario where you need to pass `...` to two different functions and want to have separate arguments)

Then `dplyr::vars()` would just call this function.

**Comment by lionel-** [comment]
also we shouldn't guard quosures with `quosure` class:

```r
quosure(!! ~explicit)
#> ~~explicit

eval_tidy(quosure(quosure(!! ~explicit)))
#> ~`_F`(explicit)
```
