### ISSUE TITLE
Unexpected value of as_closure(`[[`)

### ISSUE THREAD

**Issue by krlmlr** [hadley/rlang#75]
``` r
rlang::as_closure(`[[`)
#> function () 
#> NULL[[]]
#> <environment: base>
```

Use case: `map(some_list, `[[`, some_index)`. (By now I know I can omit the ``` `[[` ```, but I'm still not sure the behavior shown above is correct.)

**Comment by yutannihilation** [comment]
FWIW, "R internals" implies that `.GenericArgsEnv` and `.ArgsEnv` don't provide the corresponding prototypes for some primitives:

> The QC function undoc checks that all the functions prototyped in these environments are currently primitive, and that the primitives not included are better thought of as language elements (at the time of writing  
>  
>  $  $<-  &&  (  :  @  @<-  [  [[  [[<-  [<-  {  ||  ~  <-  <<-  =  
>  break  for function  if  next  repeat  return  while  
>  
> ).  
(https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Prototypes-for-primitives)

I mean, it is possible and natural that this line returns `NULL` (though I have no idea this is "correct" for rlang).

```r
 fmls <- formals(.ArgsEnv[[fn_name]] %||% .GenericArgsEnv[[fn_name]])
```
(https://github.com/hadley/rlang/blob/dce53b9bf061c0278d21a9fe17a0a138b0bc7ae1/R/fn.R#L196)

Actually, other primitives listed above behave similarly.

``` r
rlang::as_closure(`[`)
#> function () 
#> NULL[]
#> <environment: base>
rlang::as_closure(`<-`)
#> function () 
#> NULL <- NULL
#> <environment: base>
```

**Comment by lionel-** [comment]
We should handle these primitive specially then, thanks for the report.
