### ISSUE TITLE
Equivalent of seq_len starting at 2

### ISSUE THREAD

**Issue by hadley** [hadley/rlang#76]
There are quite a few algorithms where you want to skip 1 and only start comparing at element 2.

It would be useful to have a `seq()` variant to facilitate this, maybe one that only counts upwards?

**Comment by hadley** [comment]
```
seq_inc <- function(from, to) {
  if (from > to) {
    integer()
  } else {
    seq.int(from, to)
  }
}
```

**Comment by lionel-** [comment]
Or `seq2_len()` and `seq2_along()`? The latter would take a vector as second argument.

**Comment by hadley** [comment]
I was thinking ideally it would be general enough for any `n`

**Comment by lionel-** [comment]
`seq2_len()` would be defined like above.
