### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by lionel-** [hadley/rlang#78]
* I don't like `struct()` because in lisps and in C, structs are for data structures with fast member lookup. In R, attributes are stored in a linked list so that doesn't seem fitting. Should this be called `sexp()`?

* Rename `is_parsable_literal()` to `is_syntactic_literal()` so there is a connection with what we call "syntactic names".

**Comment by hadley** [comment]
Another option would be something around "metadata"

**Comment by lionel-** [comment]
maybe simply `set_attrs()`?

**Comment by hadley** [comment]
Yeah
