### ISSUE TITLE
Issue with syntactic splicing and symbolic arguments

### ISSUE THREAD

**Issue by lionel-** [hadley/rlang#80]
See if we can work around this:

```r
dots_values(!! quote(foobar))
#> Error in eval_bare(dot$expr, dot$env) (from expr.R#203) : object 'foobar' not found
```

**Comment by hadley** [comment]
This breaks dbplyr :(

**Comment by lionel-** [comment]
`!!!` is doing call splicing while `splice()` is a signal for value splicing. We should probably support both kinds of splicing because the former has to convert lists to pairlists which will have poor performance for large lists (one node allocation per element).

I think I know why `!!!` evaluates symbolic arguments, I'll look into it tomorrow.
