### ISSUE TITLE
Formatting of error messages

### ISSUE THREAD

**Issue by krlmlr** [hadley/rlang#81]
``` r
rlang::as_function(list())
#> Error: Cannot convert objects of type `list` to `function`
```

Types should not be quoted: https://github.com/hadley/dplyr/issues/2448#issuecomment-290734828.

**Comment by hadley** [comment]
Maybe should be `Can't covert list to function`?

**Comment by krlmlr** [comment]
I wonder how much of error.R in hadley/dplyr#2608 can actually move to rlang.

**Comment by lionel-** [comment]
the advantage of quoting is that you don't have to deal with grammar. E.g. this would be weird: `Cannot convert a environment to a integer`.

**Comment by hadley** [comment]
@lionel- we could fix that with `friendly_type_of(x, article = TRUE)`.  Or even dropping the articles would be fine: `Can't convert list to integer vector`
