### ISSUE TITLE
Question: will pronoun `.env` be reintroduced?

### ISSUE THREAD

**Issue by ijlyttle** [hadley/rlang#97]
Hi all,

I am (perhaps too early) trying to test-drive the new NSE DSL (and very much enjoying it).

I noticed that the `.data` pronoun was reintroduced in #85. I also remember there being an `.env` pronoun in a previous vignette.

Has the `.env` pronoun been removed from the "philosophy", or it is a matter of being patient for it to be reintroduced here?

Thanks!

**Comment by hadley** [comment]
It still exists, but it's not currently very useful because of the way that magrittr messes with environments. It's also not that important because you can use `!!` to literally insert the value into the expression rather than looking it up by name.
